language: node_js
node_js:
- node
cache:
  directories:
  - node_modules

deploy:
  provider: npm
  email: 285516193@qq.com
  api_key:
    secure: AWju8efK9/BpQQ3xbPsVcjzc4yYjjnTWVBNOR8aXPU9VK8vYsCwA2ePTfEqp3Tlr5GB/0i8IswfsET7J17NQawMaVGQhZOSPaJ2j2QkbhKx/sIZ/yDFbgf0Sg3SP+haiev0fxfiHkZb6YzWWR1G7oxLqBCu4LGcZxcq0qb2R2WmJED/hd8zZpVbWZt+iVZI38JRPRt2wyFqPmsROJ1E0pEJRQt/AOchM71HHgPhsVi3M9BAIsPgYPSpW3nZuweB5uY81R3gC9aQ5EwwqI4aNRKEg/0NfohMFX2D/La0oyleIPprW1CV8X+UlijKBuT6ffh0TOKaOPftj3GX2tQ28h0InVIrkI5ypwRiJw/doq5QejIFUG7Bbo0exFFHjAPhNJ32iqfWlqjxlx3AMZsGL03k6aFiuqLaHAu1TEN9NC+fCOEqmSXrbTuAuLsT5IOj4dbQajFgn3f7OwMCzQhBn920g6ejhJfLXYKX4XrdJLElVtHhk1MLSA8X8kCl0vfsi7a6qqRdk8rxCEb6PzNaKF7ulL/x6aP/BmF/1QdaMzqjCSousczkdmdJHv95muRyxImSGR9o/2hKQjZooJThd3uln+vTjNfe1VJ2JpZt9/XMzBWz6eqMDDgRvyS2i0gi74hQwqp5Q2IDXalDgiyqKKux2IZQfcriJJhuxqIfmYbU=
  on:
    tags: true
    repo: yunkeCN/utils
  tag: next